apiVersion: apps/v1 
kind: Deployment
metadata:
  name: qotd-qrcode
  namespace: qotd
  labels:
    app: qotd
spec:
  selector:
    matchLabels:
      app: qotd-qrcode
  replicas: 1
  template:
    metadata:
      labels:
        app: qotd-qrcode
    spec:
      containers:
      - name: qotd-qrcode
        image: registry.gitlab.com/quote-of-the-day/qotd-qrcode/main:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-qrcode
  namespace: qotd
  labels:
    app: qotd
spec:
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: qotd-qrcode
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-qrcode
  namespace: qotd
  labels:
    app: qotd
spec:
  to:
    kind: Service
    name: qotd-qrcode
    weight: 100
  port:
    targetPort: 9080
  wildcardPolicy: None
