kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-engraving
  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-engraving
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qotd-engraving
    spec:
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 25m
              memory: 40Mi
          terminationMessagePath: /dev/termination-log
          name: qotd-engraving
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: LOCAL_LOGGING
              value: 'false'
            - name: ENABLE_INSTANA
              value: 'true'
          ports:
            - name: http
              containerPort: 3006
              protocol: TCP
            - name: svc
              containerPort: 8086
              protocol: TCP
          imagePullPolicy: Always
          image: registry.gitlab.com/quote-of-the-day/qotd-engraving-service:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-engraving
  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
  selector:
    app: qotd-engraving
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-engraving-svc
  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: svc
  selector:
    app: qotd-engraving
